name: Keep Supabase Project Alive

on:
  schedule:
    # מריץ את הפעולה מדי 3 ימים בשעה 12:30 UTC
    - cron: '30 12 */3 * *'
  workflow_dispatch: # מאפשר הרצה ידנית בלחיצת כפתור

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Root Endpoint
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -L "https://fruzzkgdjaludyxbsymi.supabase.co")
          
          echo "Supabase status code: $response"
          
          if [ "$response" -eq 000 ]; then
            echo "Failed to connect to Supabase"
            exit 1
          fi
          
          echo "Successfully reached Supabase project!"